### ISSUE TITLE
NPM

### ISSUE THREAD

**Issue by webdev03** [SpellCheckJS/nodejs-client#5]
Add it to NPM!

**Comment by webdev03** [comment]
Like, on the registry I mean.

**Comment by hello-smile6** [comment]
> Add it to NPM!

Good idea, but I can't. I'm not sharing my email. For now, you have to install using github.

**Comment by webdev03** [comment]
Ok

**Comment by hello-smile6** [comment]
> Ok

You can now open SpellCheckJS via https://git.io/spellcheckjs
